import React,{createContext,useContext,useEffect,useMemo,useState}from'react';import{supabase,supabaseConfigured}from'../lib/supabase';import{demoCategorias,demoSubcategorias,demoProductos,demoColores,demoProductoColores,demoPedidos}from'../data/demoData';
const C=createContext();export const useApp=()=>useContext(C);
export function AppProvider({children}){const[loading,setLoading]=useState(true),[categorias,setCategorias]=useState([]),[subcategorias,setSubcategorias]=useState([]),[productos,setProductos]=useState([]),[colores,setColores]=useState([]),[productoColores,setProductoColores]=useState([]),[pedidos,setPedidos]=useState([]),[cart,setCart]=useState(()=>JSON.parse(localStorage.getItem('cart')||'[]')),[toast,setToast]=useState(null);useEffect(()=>{localStorage.setItem('cart',JSON.stringify(cart))},[cart]);const notify=(m,t='ok')=>{setToast({m,t});setTimeout(()=>setToast(null),3000)};async function load(){setLoading(true);try{if(supabaseConfigured){const[t1,t2,t3,t4,t5,t6]=await Promise.all([supabase.from('categorias').select('*').order('orden_visual'),supabase.from('subcategorias').select('*').order('orden_visual'),supabase.from('productos').select('*').order('id_producto'),supabase.from('colores').select('*').order('nombre'),supabase.from('producto_colores').select('*'),supabase.from('pedidos').select('*').order('fecha_alta',{ascending:false})]);setCategorias(t1.data||[]);setSubcategorias(t2.data||[]);setProductos(t3.data||[]);setColores(t4.data||[]);setProductoColores(t5.data||[]);setPedidos(t6.data||[])}else{setCategorias(demoCategorias);setSubcategorias(demoSubcategorias);setProductos(demoProductos);setColores(demoColores);setProductoColores(demoProductoColores);setPedidos(demoPedidos)}}catch(e){console.error(e);notify('Error cargando datos. Usando demo.','err');setCategorias(demoCategorias);setSubcategorias(demoSubcategorias);setProductos(demoProductos);setColores(demoColores);setProductoColores(demoProductoColores);setPedidos(demoPedidos)}setLoading(false)}useEffect(()=>{load()},[]);
const getCat=id=>categorias.find(x=>x.id_categoria==id)?.nombre||'';const getSub=id=>subcategorias.find(x=>x.id_subcategoria==id)?.nombre||'';const getColor=id=>colores.find(x=>x.id_color==id);const coloresProducto=id=>productoColores.filter(pc=>pc.id_producto==id&&pc.activo!==false).map(pc=>getColor(pc.id_color)).filter(Boolean);
function addCart(producto,color,cantidad=1){const key=`${producto.id_producto}-${color?.id_color||'sincolor'}`;setCart(prev=>{const ex=prev.find(i=>i.key===key);if(ex)return prev.map(i=>i.key===key?{...i,cantidad:i.cantidad+cantidad}:i);return[...prev,{key,id_producto:producto.id_producto,producto:producto.nombre,categoria:getCat(producto.id_categoria),subcategoria:getSub(producto.id_subcategoria),id_color:color?.id_color||null,color:color?.nombre||null,color_hex:color?.codigo_hex||null,cantidad,detalle:producto.detalle_manual,precio_base:producto.precio_base||0}]});notify('Producto agregado al carrito')}
function updateQty(key,cantidad){setCart(p=>p.map(i=>i.key===key?{...i,cantidad:Math.max(1,cantidad)}:i))}function removeCart(key){setCart(p=>p.filter(i=>i.key!==key))}function clearCart(){setCart([])}
async function crearPedido(cliente){const codigo=`PED-${String(Date.now()).slice(-6)}`;const msg=buildClienteMsg(codigo,cliente,cart);const pedido={codigo_pedido:codigo,nombre_cliente:cliente.nombre,telefono_cliente:cliente.telefono,observaciones_cliente:cliente.observaciones,estado:'PENDIENTE_PRESUPUESTAR',mensaje_whatsapp_cliente:msg};if(supabaseConfigured){const{data,error}=await supabase.from('pedidos').insert(pedido).select().single();if(error)throw error;const detalles=cart.map(i=>({id_pedido:data.id_pedido,id_producto:i.id_producto,id_color:i.id_color,nombre_categoria:i.categoria,nombre_subcategoria:i.subcategoria,nombre_producto:i.producto,nombre_color:i.color,cantidad:i.cantidad,detalle_producto:i.detalle,precio_base_original:i.precio_base}));await supabase.from('detalle_pedido').insert(detalles)}setPedidos(p=>[{...pedido,id_pedido:Date.now(),fecha_alta:new Date().toISOString(),total_final:0},...p]);clearCart();return{codigo,msg}}
function buildClienteMsg(codigo,c,items){return`Solicitud de presupuesto\nCódigo: ${codigo}\n\nCliente:\nNombre: ${c.nombre}\nTeléfono: ${c.telefono}\n\nDetalle:\n${items.map(i=>`\nCategoría: ${i.categoria}\nSubcategoría: ${i.subcategoria}\nProducto: ${i.producto}\n${i.color?`Color: ${i.color}\n`:''}Cantidad: ${i.cantidad}\nDetalle: ${i.detalle||'-'}`).join('\n')}\n\nObservaciones:\n${c.observaciones||'-'}\n\nQuedo atento al presupuesto. Muchas gracias.`}
const value={loading,categorias,setCategorias,subcategorias,setSubcategorias,productos,setProductos,colores,setColores,productoColores,setProductoColores,pedidos,setPedidos,cart,addCart,updateQty,removeCart,clearCart,crearPedido,coloresProducto,getCat,getSub,notify,supabaseConfigured};return <C.Provider value={value}>{children}{toast&&<div className={'toast '+toast.t}>{toast.m}</div>}</C.Provider>}
